<?xml version="1.0"?>
<!-- by lufer -->
<!DOCTYPE PHONE_RECORDS SYSTEM "calls.dtd">
<!--
<!DOCTYPE PHONE_RECORDS [
<!ELEMENT PHONE_RECORDS ( CALL)* >

<!ELEMENT CALL ( FROM, DATE, TIME, DESTINATION, DURATION, CALL_PROMOTION?)>

<!ELEMENT FROM ( #PCDATA ) >
<!ELEMENT DATE ( #PCDATA ) >

<!ELEMENT TIME EMPTY >
<!ATTLIST TIME
	HOUR NMTOKEN #REQUIRED
	MINUTE NMTOKEN #REQUIRED
>

<!ELEMENT DESTINATION ( #PCDATA ) >
<!ATTLIST DESTINATION
	CITY NMTOKEN #REQUIRED
	COUNTRY NMTOKEN #REQUIRED
	STATE NMTOKEN #IMPLIED >

<!ELEMENT DURATION EMPTY >
<!ATTLIST DURATION
	HOURS NMTOKEN #REQUIRED 
	MINUTES NMTOKEN #REQUIRED >

<!ELEMENT CALL_PROMOTION ( #PCDATA ) >

]>
-->
<?xml-stylesheet type="text/xsl" href="calls.xsl"?>

<PHONE_RECORDS>
  <!-- Call Record 1 -->
  <CALL>
    <FROM>703-433-5678</FROM>
    <DATE>5/5/2017</DATE>
    <TIME HOUR="19" MINUTE="32"/>
    <DESTINATION STATE="California" CITY="Sunnyvale" COUNTRY="US">
      510-798-8390
    </DESTINATION>
    <DURATION HOURS="1" MINUTES="15"/>
  </CALL>
  <!-- Call Record 2 -->
  <CALL>
    <FROM>703-374-2363</FROM>
    <DATE>5/15/2017</DATE>
    <TIME HOUR="20" MINUTE="15"/>
    <DESTINATION CITY="Birmingham" COUNTRY="UK">
      44-121-739-4294
    </DESTINATION>
    <!--<DURATION HOURS="0" MINUTES="30">ola
      <A>ok</A>
    </DURATION>-->
    <DURATION HOURS="0" MINUTES="30"/>
    <CALL_PROMOTION>HALF_PRICE</CALL_PROMOTION>
  </CALL>

  <CALL>
    <FROM>703-839-7384</FROM>
    <DATE>8/3/2017</DATE>
    <TIME HOUR="21" MINUTE="32"/>
    <DESTINATION CITY="FairFax" COUNTRY="US">703-839-8384</DESTINATION>
    <DURATION HOURS="0" MINUTES="12"/>
  </CALL>
  <CALL>
    <FROM>839-374-2363</FROM>
    <DATE>9/15/2017</DATE>
    <TIME HOUR="13" MINUTE="23"/>
    <DESTINATION CITY="WesternIsles" COUNTRY="UK">44-145-904-8384</DESTINATION>
    <DURATION HOURS="1" MINUTES="2"/>
  </CALL>

  <CALL>
    <FROM>839-374-2363 OLA</FROM>
    <DATE>9/15/2017</DATE>
    <TIME HOUR="13" MINUTE="23"/>
    <DESTINATION CITY="WesternIsles" COUNTRY="UK">44-145-904-8384</DESTINATION>
    <DURATION HOURS="1" MINUTES="2"/>
  </CALL>

  <CALL>
    <FROM>703-433-5678</FROM>
    <DATE>5/5/2018</DATE>
    <TIME HOUR="19" MINUTE="32"/>
    <DESTINATION STATE="California" CITY="Sunnyvale" COUNTRY="US">
      510-798-8390
    </DESTINATION>
    <DURATION HOURS="1" MINUTES="15"/>
  </CALL>

  <CALL>
    <FROM>703-433-5678</FROM>
    <DATE>5/5/2018</DATE>
    <TIME HOUR="19" MINUTE="32"/>
    <DESTINATION STATE="California" CITY="Sunnyvale" COUNTRY="US">
      510-798-8390
    </DESTINATION>
    <DURATION HOURS="1" MINUTES="15"/>
  </CALL>
</PHONE_RECORDS>
