=== JoshuaJones27/ISI/Documentos XML dos acetatos/AddressList.dtd
<!ELEMENT ADDRESSLIST ( ADDRESS)+>

<!ELEMENT ADDRESS ( WORK+, HOME?)>
<!ATTLIST ADDRESS NAME  CDATA #REQUIRED>

<!ELEMENT WORK ( STREET, CITY, STATE, COUNTRY)>
<!ELEMENT HOME ( STREET, CITY, STATE, COUNTRY )>

<!ELEMENT STREET ( #PCDATA )>
<!ELEMENT CITY ( #PCDATA )>
<!ELEMENT STATE ( #PCDATA) >
<!ELEMENT COUNTRY ( #PCDATA)>

=== JoshuaJones27/ISI/Documentos XML dos acetatos/AddressList _II.xml
<?xml version="1.0"?>
<!--<!DOCTYPE ADDRESSLIST SYSTEM "AddressList.dtd">-->

<!DOCTYPE ADDRESSLIST
[
<!ELEMENT ADDRESSLIST ( ADDRESS)+>
<!ELEMENT ADDRESS ( WORK+, HOME?)>
<!ATTLIST ADDRESS NAME  CDATA #REQUIRED>
<!ELEMENT WORK ( STREET, CITY, STATE, COUNTRY)>
<!ELEMENT HOME ( STREET, CITY, STATE, COUNTRY )>
<!ELEMENT STREET ( #PCDATA )>
<!ELEMENT CITY ( #PCDATA )>
<!ELEMENT STATE ( #PCDATA) >
<!ELEMENT COUNTRY ( #PCDATA)>
]>

<ADDRESSLIST>
 	<ADDRESS NAME="Miss. Ex M. Elle">
		<WORK>
		<STREET>22, WWW Street</STREET> 
	        <CITY>Cambridge</CITY>
		<STATE>MA</STATE>
		<COUNTRY>USA</COUNTRY>
		</WORK>
		<WORK>
		<STREET>44, Triple W Street</STREET>
	        <CITY>Cambridge</CITY>
		<STATE>MA</STATE>
		<COUNTRY>USA</COUNTRY>
		</WORK>
	</ADDRESS>
	<ADDRESS NAME="Mr. Ex S. Elle">
		<WORK>
			<STREET>34 WWW Street</STREET> 
	        	<CITY>Palo Alto</CITY>
			<STATE>CA</STATE>
			<COUNTRY>USA</COUNTRY>
		</WORK>
		<HOME>
		<STREET>23 WWW Street</STREET> 
	        <CITY>Palo Alto</CITY>
		<STATE>CA</STATE>
		<COUNTRY>USA</COUNTRY>
		</HOME>
	</ADDRESS>
</ADDRESSLIST>

=== JoshuaJones27/ISI/Documentos XML dos acetatos/AddressList.xml
<?xml version="1.0"?>
<!DOCTYPE ADDRESSLIST SYSTEM "AddressList.dtd">
<ADDRESSLIST>
 	<ADDRESS NAME="Miss. Ex M. Elle">
		<WORK>
		<STREET>22, WWW Street</STREET> 
	        <CITY>Cambridge</CITY>
		<STATE>MA</STATE>
		<COUNTRY>USA</COUNTRY>
		</WORK>
		<WORK>
		<STREET>44, Triple W Street</STREET>
	        <CITY>Cambridge</CITY>
		<STATE>MA</STATE>
		<COUNTRY>USA</COUNTRY>
		</WORK>
	</ADDRESS>
	<ADDRESS NAME="Mr. Ex S. Elle">
		<WORK>
			<STREET>34 WWW Street</STREET> 
	        	<CITY>Palo Alto</CITY>
			<STATE>CA</STATE>
			<COUNTRY>USA</COUNTRY>
		</WORK>
		<HOME>
		<STREET>23 WWW Street</STREET> 
	        <CITY>Palo Alto</CITY>
		<STATE>CA</STATE>
		<COUNTRY>USA</COUNTRY>
		</HOME>
	</ADDRESS>
</ADDRESSLIST>
